import { Department, Doctor, UserSession, UserRole } from './index.js';

export const SEED_DEPARTMENTS: Department[] = [
  {
    id: 'dept_card',
    code: 'CARDIOLOGY',
    name: 'Cardiology & Heart Center',
    description: 'Comprehensive cardiovascular care, interventional cardiology, electrophysiology, and advanced cardiac rehabilitation.',
    location: 'Building B, 3rd Floor',
    emergencySupport: true,
    icon: 'Heart',
  },
  {
    id: 'dept_ped',
    code: 'PEDIATRICS',
    name: 'Pediatrics & Neonatology',
    description: 'Specialized compassionate healthcare for newborns, infants, children, and adolescents with Level III NICU.',
    location: 'Building C, 2nd Floor',
    emergencySupport: true,
    icon: 'Baby',
  },
  {
    id: 'dept_neuro',
    code: 'NEUROLOGY',
    name: 'Neurology & Brain Institute',
    description: 'Advanced diagnostic, neurovascular, and comprehensive neurosurgical care for complex nervous system disorders.',
    location: 'Building B, 4th Floor',
    emergencySupport: true,
    icon: 'Brain',
  },
  {
    id: 'dept_ortho',
    code: 'ORTHOPEDICS',
    name: 'Orthopedic Surgery & Joint Center',
    description: 'Pioneering robotic joint replacements, complex spine reconstruction, arthroscopic surgery, and sports medicine.',
    location: 'Building A, 2nd Floor',
    emergencySupport: false,
    icon: 'Bone',
  },
  {
    id: 'dept_oncol',
    code: 'ONCOLOGY',
    name: 'Comprehensive Cancer Center',
    description: 'Multidisciplinary precision cancer therapeutics, immunotherapy, cellular therapies, and radiation oncology.',
    location: 'Building C, 4th Floor',
    emergencySupport: false,
    icon: 'Shield',
  },
  {
    id: 'dept_emg',
    code: 'EMERGENCY',
    name: 'Emergency & Trauma Department',
    description: '24/7 acute emergency medical and surgical triage care with Level 1 trauma facilities.',
    location: 'Building A, Ground Floor',
    emergencySupport: true,
    icon: 'Activity',
  },
];

export const SEED_DOCTORS: Doctor[] = [
  {
    id: 'doc_sarah',
    name: 'Dr. Sarah Patel',
    title: 'Dr. Sarah Patel, MD, FACC',
    specialty: 'Cardiologist',
    departmentId: 'dept_card',
    qualification: 'MD (Harvard), Fellowship Interventional Cardiology',
    experienceYears: 16,
    rating: 4.96,
    reviewCount: 248,
    consultationFee: 150.0,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['09:00 AM', '10:30 AM', '02:00 PM', '03:30 PM'],
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    bio: 'World-renowned interventional cardiologist specializing in coronary artery disease and non-invasive valve repair.',
    phone: '+1 (555) 123-4567',
    email: 'sarah.patel@hospital.com',
  },
  {
    id: 'doc_michael',
    name: 'Dr. Michael Chang',
    title: 'Dr. Michael Chang, MD, FAAP',
    specialty: 'Pediatrician',
    departmentId: 'dept_ped',
    qualification: 'MD (Stanford), Residency in Pediatric Critical Care',
    experienceYears: 12,
    rating: 4.91,
    reviewCount: 195,
    consultationFee: 120.0,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    availableSlots: ['08:30 AM', '10:00 AM', '01:00 PM', '02:30 PM'],
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    bio: 'Dedicated pediatrician specializing in neonatal development, preventative wellness, and pediatric acute care.',
    phone: '+1 (555) 234-5678',
    email: 'michael.chang@hospital.com',
  },
  {
    id: 'doc_elena',
    name: 'Dr. Elena Rostova',
    title: 'Dr. Elena Rostova, MD, PhD',
    specialty: 'Neurologist',
    departmentId: 'dept_neuro',
    qualification: 'MD, PhD (Johns Hopkins), Vascular Neurology Fellowship',
    experienceYears: 14,
    rating: 4.94,
    reviewCount: 186,
    consultationFee: 180.0,
    availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['09:00 AM', '11:30 AM', '01:30 PM', '04:00 PM'],
    avatarUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&q=80&w=400',
    bio: 'Director of Stroke Care & Comprehensive Neurovascular Therapeutics.',
    phone: '+1 (555) 345-6789',
    email: 'elena.rostova@hospital.com',
  },
  {
    id: 'doc_david',
    name: 'Dr. David Kim',
    title: 'Dr. David Kim, MD, FAAOS',
    specialty: 'Orthopedic Surgeon',
    departmentId: 'dept_ortho',
    qualification: 'MD (Columbia), Fellowship in Adult Joint Reconstruction',
    experienceYears: 18,
    rating: 4.89,
    reviewCount: 312,
    consultationFee: 200.0,
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    availableSlots: ['08:00 AM', '11:00 AM', '02:00 PM', '04:30 PM'],
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    bio: 'Pioneer in minimally invasive total knee and anterior approach hip replacements.',
    phone: '+1 (555) 456-7890',
    email: 'david.kim@hospital.com',
  },
  {
    id: 'doc_priya',
    name: 'Dr. Priya Nair',
    title: 'Dr. Priya Nair, MD',
    specialty: 'Oncologist',
    departmentId: 'dept_oncol',
    qualification: 'MD (Yale), Medical Oncology Fellowship (MSKCC)',
    experienceYears: 15,
    rating: 4.97,
    reviewCount: 220,
    consultationFee: 190.0,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    availableSlots: ['09:30 AM', '11:00 AM', '02:00 PM', '03:45 PM'],
    avatarUrl: 'https://images.unsplash.com/photo-1594824813571-638f02614d3f?auto=format&fit=crop&q=80&w=400',
    bio: 'Leader in precision targeted cancer therapies and clinical genomic oncology research.',
    phone: '+1 (555) 567-8901',
    email: 'priya.nair@hospital.com',
  },
  {
    id: 'doc_marcus',
    name: 'Dr. Marcus Vance',
    title: 'Dr. Marcus Vance, MD, FACEP',
    specialty: 'Emergency Physician',
    departmentId: 'dept_emg',
    qualification: 'MD (UCLA), Emergency Medicine Residency (Emory)',
    experienceYears: 20,
    rating: 4.92,
    reviewCount: 410,
    consultationFee: 160.0,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableSlots: ['07:00 AM', '12:00 PM', '05:00 PM', '10:00 PM'],
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400',
    bio: 'Chief Medical Officer and Emergency Medical Director managing hospital critical care readiness.',
    phone: '+1 (555) 678-9012',
    email: 'marcus.vance@hospital.com',
  },
];

export const PRESET_STAFF_USERS: Record<UserRole, UserSession> = {
  ADMIN: {
    id: 'usr_admin',
    username: 'admin',
    email: 'arthur.vance@hospital.com',
    name: 'Dr. Arthur Vance (Director)',
    role: 'ADMIN',
  },
  DOCTOR: {
    id: 'usr_sarah',
    username: 'dr_sarah',
    email: 'sarah.patel@hospital.com',
    name: 'Dr. Sarah Patel, MD',
    role: 'DOCTOR',
    departmentId: 'dept_card',
    doctorId: 'doc_sarah',
  },
  RECEPTIONIST: {
    id: 'usr_reception',
    username: 'reception',
    email: 'sam.reception@hospital.com',
    name: 'Samuel Rivera (OPD Desk)',
    role: 'RECEPTIONIST',
  },
  COMPLIANCE_AUDITOR: {
    id: 'usr_auditor',
    username: 'auditor',
    email: 'eleanor.compliance@hospital.com',
    name: 'Eleanor Campbell',
    role: 'COMPLIANCE_AUDITOR',
  },
  CHIEF_MEDICAL_OFFICER: {
    id: 'usr_cmo',
    username: 'cmo',
    email: 'cmo@hospital.com',
    name: 'Dr. Marcus Vance (CMO)',
    role: 'CHIEF_MEDICAL_OFFICER',
    departmentId: 'dept_emg',
    doctorId: 'doc_marcus',
  },
  NURSE: {
    id: 'usr_nurse',
    username: 'nurse_jane',
    email: 'jane.rn@hospital.com',
    name: 'Jane Miller, RN',
    role: 'NURSE',
    departmentId: 'dept_card',
  },
  PHARMACIST: {
    id: 'usr_pharm',
    username: 'pharm_dave',
    email: 'dave.pharm@hospital.com',
    name: 'David Miller, PharmD',
    role: 'PHARMACIST',
  },
  LAB_TECHNICIAN: {
    id: 'usr_lab',
    username: 'lab_tech',
    email: 'lab.tech@hospital.com',
    name: 'Alex Rivera, MLS',
    role: 'LAB_TECHNICIAN',
  },
  PATIENT: {
    id: 'usr_paulo',
    username: 'paulo',
    email: 'paulo.hubert@example.com',
    name: 'Paulo Hubert',
    role: 'PATIENT',
    patientId: 'pat_1',
  },
};
