FROM node:20-alpine AS builder

WORKDIR /app

# Copy root workspace configs
COPY package.json tsconfig.json ./
COPY packages/ packages/
COPY apps/ apps/

RUN npm install
RUN npm run build:packages

ARG SERVICE_NAME
RUN npm run --workspace=${SERVICE_NAME} build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app /app

ARG SERVICE_NAME
ENV APP_DIR=${SERVICE_NAME}

EXPOSE 4000 4001 4002 4003 4004 4005

CMD ["node", "scripts/start-all.js"]
